### PR TITLE
Fix Tidy3d compatibility: Fill in zero valued off-diagonal epsilon

### PR DESCRIPTION
**Pull request by jan-david-fischbach**
@flaport @momchil-flex

### CODE REVIEW

**Comment by jan-david-fischbach** [comment]
Just realized, that this makes it incompatible to older versions of tidy3d. Will have to build in a check...

**Comment by jan-david-fischbach** [comment]
Should be ready to merge now

**Comment by flaport** [comment]
Thanks Jan-David!

**Comment by flaport** [comment]
Fix will be available in 0.3.4

**Pull request merged**
